# Generated by Django 3.0.8 on 2020-07-20 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.NullBooleanField(default=None),
        ),
    ]
